//! Integration-style tests for high-level install/update/debloat behavior.
//!
//! Tests focus on canonical path installs, metadata-driven lifecycle behavior,
//! non-destructive updates, and symlink handling during cleanup.

use std::fs;

#[cfg(unix)]
use std::os::unix::fs::symlink;

use tempfile::tempdir;

use crate::constants::Platform;
use crate::meta::load_manifest;
use crate::{run, Command};

fn version() -> &'static str {
    env!("CARGO_PKG_VERSION")
}

fn claude_platform() -> Platform {
    Platform { root: ".claude" }
}

#[test]
fn install_creates_meta_and_canonical_files() {
    let home = tempdir().expect("tempdir should be created");
    let result = run(Command::Install, home.path()).expect("install should succeed");

    assert!(result.contains("Installed configuration version"));

    let claude_agent = home.path().join(".claude/agents/rust-specialist.md");
    assert!(claude_agent.exists());
    assert!(!home
        .path()
        .join(".claude/agents")
        .join(format!("rafaelcmm-{}-rust-specialist.md", version()))
        .exists());

    let copilot_skill = home.path().join(".copilot/skills/clean-code/SKILL.md");
    assert!(copilot_skill.exists());

    let manifest = load_manifest(home.path(), claude_platform())
        .expect("manifest load should succeed")
        .expect("manifest should exist");
    assert_eq!(manifest.version, version());
    assert!(manifest.managed_files.contains("_meta.md"));
    assert!(manifest.managed_files.contains("agents/rust-specialist.md"));
    assert!(manifest
        .managed_files
        .contains("skills/clean-code/SKILL.md"));
    assert!(manifest.managed_directories.contains("agents"));
    assert!(manifest.managed_directories.contains("skills"));
    assert!(manifest.managed_directories.contains("skills/clean-code"));
}

#[test]
fn second_install_requests_update() {
    let home = tempdir().expect("tempdir should be created");
    run(Command::Install, home.path()).expect("first install should succeed");

    let second =
        run(Command::Install, home.path()).expect("second install should succeed with no changes");
    assert_eq!(
        second,
        "Configuration already installed. Run `update` instead.".to_string()
    );
}

#[test]
fn update_reports_up_to_date_when_versions_match() {
    let home = tempdir().expect("tempdir should be created");
    run(Command::Install, home.path()).expect("install should succeed");

    let message = run(Command::Update, home.path()).expect("update should succeed");
    assert_eq!(message, "Configuration is already up to date.".to_string());
}

#[test]
fn update_bootstraps_when_no_install_exists() {
    let home = tempdir().expect("tempdir should be created");
    let message = run(Command::Update, home.path()).expect("update should succeed");

    assert!(message.contains("Updated configuration to version"));
    assert!(home.path().join(".claude/_meta.md").exists());
    assert!(home
        .path()
        .join(".claude/agents/rust-specialist.md")
        .exists());
}

#[test]
fn update_migrates_legacy_prefixed_install_in_place() {
    let home = tempdir().expect("tempdir should be created");

    let legacy_agent = home
        .path()
        .join(".claude/agents")
        .join(format!("rafaelcmm-{}-rust-specialist.md", version()));
    fs::create_dir_all(legacy_agent.parent().expect("legacy parent should exist"))
        .expect("legacy parent should be created");
    fs::write(&legacy_agent, "legacy").expect("legacy file should be created");
    fs::write(
        home.path().join(".claude/_meta.md"),
        format!(
            "---\nversion: {}\n---\n\nThis file is automatically generated.\n",
            version()
        ),
    )
    .expect("legacy metadata should be written");

    let message = run(Command::Update, home.path()).expect("update should succeed");

    assert!(message.contains("Updated configuration to version"));
    assert!(!legacy_agent.exists());
    assert!(home
        .path()
        .join(".claude/agents/rust-specialist.md")
        .exists());

    let manifest = load_manifest(home.path(), claude_platform())
        .expect("manifest load should succeed")
        .expect("manifest should exist after migration");
    assert!(manifest.managed_files.contains("agents/rust-specialist.md"));
    assert!(manifest.managed_directories.contains("agents"));
}

#[test]
fn debloat_removes_only_managed_content() {
    let home = tempdir().expect("tempdir should be created");
    run(Command::Install, home.path()).expect("install should succeed");

    let user_file = home.path().join(".claude/agents/my-custom-agent.md");
    fs::create_dir_all(user_file.parent().expect("parent must exist"))
        .expect("parent dir should be created");
    fs::write(&user_file, "custom").expect("custom file should be created");

    run(Command::Debloat, home.path()).expect("debloat should succeed");

    let managed = home.path().join(".claude/agents/rust-specialist.md");
    assert!(!managed.exists());
    assert!(user_file.exists());
    assert!(!home.path().join(".claude/_meta.md").exists());
}

#[cfg(unix)]
#[test]
fn debloat_does_not_follow_symlinked_managed_dir() {
    let home = tempdir().expect("tempdir should be created");
    let outside = tempdir().expect("outside tempdir should be created");

    let outside_file = outside.path().join("keep.txt");
    fs::write(&outside_file, "do not delete").expect("outside file should be created");

    let agents = home.path().join(".claude/agents");
    fs::create_dir_all(&agents).expect("agents dir should be created");
    let link_path = agents.join("rafaelcmm-symlink");
    symlink(outside.path(), &link_path).expect("symlink should be created");

    run(Command::Debloat, home.path()).expect("debloat should succeed");

    assert!(outside_file.exists());
    assert!(!link_path.exists());
}

#[cfg(unix)]
#[test]
fn update_does_not_follow_symlinked_managed_dir() {
    let home = tempdir().expect("tempdir should be created");
    let outside = tempdir().expect("outside tempdir should be created");

    let outside_file = outside.path().join("keep-update.txt");
    fs::write(&outside_file, "do not delete").expect("outside file should be created");

    let rules = home.path().join(".cursor/rules");
    fs::create_dir_all(&rules).expect("rules dir should be created");
    let link_path = rules.join("rafaelcmm-symlink");
    symlink(outside.path(), &link_path).expect("symlink should be created");

    run(Command::Update, home.path()).expect("update should succeed");

    assert!(outside_file.exists());
    assert!(!link_path.exists());
}
